### ISSUE TITLE
timeseries query doesnt match groupby

### ISSUE THREAD

**Issue by pdeva** [apache/incubator-druid#701]
reference discussion:
https://groups.google.com/forum/#!topic/druid-development/BSpDmAq-7Jk

i dont have the exact query, but i remember doing just a doubleSum.
there was only 1 row with 1 metric column in druid. minute level granularity was asked for.

thing to notice:
the row is stored at timestamp between 2 minute boundaries (04:33:25).
the query on the other hand, asks for minute level granularity, so values at 04:33 and 04:34 are returned by timeseries (though not so by groupby).

**Comment by fjy** [comment]
I believe this has been fixed. Please reopen if it is not the case.

**Comment by gianm** [comment]
I think timeseries still zero fills and groupBy still does not.

**Comment by xvrl** [comment]
Timeseries should not be zero-filling anymore. We've fixed issues around that a while back.

**Comment by gianm** [comment]
Ok, it does zero-fill by default, but I forgot about the skipEmptyBuckets thing that turns it off. I think I can be forgiven for that since it's not documented :)

I'll write some docs for it, but also wonder if it would make sense to change the default behavior in the future. I think zero-filling would be better off by default.

**Comment by vogievetsky** [comment]
I think that with DSQL this ticket can be closed, I doubt you would ever change skipEmptyBuckets defaults. @gianm thoughts?
